set_project("scrap_mechanic_sdk")
set_version("0.1.2")
set_languages("c++20")
set_toolchains("clang-cl")

add_requires("minhook", "zydis 4.1.1")

target("memorylib")
    set_kind("static")
    add_files("memorylib/src/memorylib.cpp")
    add_packages("minhook", "zydis")
    add_includedirs("memorylib/include", {public = true})
    add_defines("WIN32_LEAN_AND_MEAN", "NOMINMAX", "UNICODE", "_UNICODE")
    add_cxxflags("/EHsc", "/W4", "/permissive-")
    add_syslinks("kernel32")

target("scrap_mechanic_sdk")
    set_kind("shared")
    set_targetdir("build/windows/x64/release")
    add_files("src/sdk.cpp", "src/lua_inspector.cpp", "src/events.cpp", "src/lua_hooks.cpp", "src/lua_reload_coordinator.cpp", "src/lua_diagnostics.cpp", "src/runtime.cpp")
    add_deps("memorylib")
    add_includedirs("include", {public = true})
    add_defines("WIN32_LEAN_AND_MEAN", "NOMINMAX", "UNICODE", "_UNICODE", "SCRAP_MECHANIC_SDK_BUILD")
    add_cxxflags("/EHsc", "/W4", "/permissive-")
    add_syslinks("kernel32")
